### ISSUE TITLE
화상채팅방[5] 버그 수정

### ISSUE THREAD

**Issue by jyo-jyo** [boostcampwm-2021/web12-sooltreaming#63]
### Description
거지같은 버그 수정

### To do
- [x] 스트림 받아오기 전에 나오는 어쩌고 저쩌고

**Comment by alittlekitten** [comment]
? ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by pyo-sh** [comment]
> 대체 거지는 언제 치우는거죠?


![image](https://user-images.githubusercontent.com/55688122/141734933-0aa17976-de67-4497-82fb-6b50b44c1504.png)
